// Fetches all 48 World Cup 2026 squads from football-data.org
// and generates src/lib/players.js (1,248 players).
//
// Run once after squads are confirmed:
//   node scripts/fetch-squads.mjs
//
// Requires FOOTBALL_DATA_API_KEY in .env

import { writeFileSync, readFileSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

const root = dirname(dirname(fileURLToPath(import.meta.url)));

// Read API key from .env
const envPath = join(root, '.env');
const env = Object.fromEntries(
  readFileSync(envPath, 'utf8')
    .split('\n')
    .filter(l => l.includes('=') && !l.startsWith('#'))
    .map(l => { const i = l.indexOf('='); return [l.slice(0, i).trim(), l.slice(i + 1).trim()]; })
);
const API_KEY = env.FOOTBALL_DATA_API_KEY;

if (!API_KEY) {
  console.error('FOOTBALL_DATA_API_KEY not found in .env');
  process.exit(1);
}

const headers = { 'X-Auth-Token': API_KEY };

async function fetchJson(url) {
  const res = await fetch(url, { headers });
  if (!res.ok) throw new Error(`${res.status} ${res.statusText} — ${url}`);
  return res.json();
}

// Slight pause between requests to respect rate limits (10 req/min on free tier)
const sleep = (ms) => new Promise(r => setTimeout(r, ms));

console.log('Fetching WC 2026 teams…');
const { teams } = await fetchJson('https://api.football-data.org/v4/competitions/WC/teams');
console.log(`Got ${teams.length} teams`);

const players = [];
const teamNames = [];

for (const team of teams) {
  teamNames.push({ name: team.name, shortName: team.shortName, code: team.tla });

  // Fetch full team details to get squad
  await sleep(6500); // free tier: 10 req/min = 1 req/6s
  let squad = team.squad ?? [];

  if (!squad.length) {
    try {
      console.log(`  Fetching squad for ${team.name}…`);
      const detail = await fetchJson(`https://api.football-data.org/v4/teams/${team.id}`);
      squad = detail.squad ?? [];
    } catch (e) {
      console.warn(`  Could not fetch squad for ${team.name}: ${e.message}`);
    }
  }

  for (const p of squad) {
    if (p.name) {
      players.push({
        name: p.name,
        team: team.name,
        teamCode: team.tla,
        position: p.position ?? null,
      });
    }
  }

  console.log(`  ${team.name} (${team.tla}): ${squad.length} players`);
}

// Sort: by team, then name
players.sort((a, b) => a.teamCode.localeCompare(b.teamCode) || a.name.localeCompare(b.name));
teamNames.sort((a, b) => a.name.localeCompare(b.name));

const out = `// Auto-generated by scripts/fetch-squads.mjs — do not edit manually.
// Run: node scripts/fetch-squads.mjs   (requires FOOTBALL_DATA_API_KEY in .env)
// ${players.length} players across ${teamNames.length} teams.

export const PLAYERS = ${JSON.stringify(players, null, 2)};

export const TEAM_NAMES = ${JSON.stringify(teamNames, null, 2)};
`;

const outPath = join(root, 'src/lib/players.js');
writeFileSync(outPath, out);
console.log(`\nWrote ${players.length} players and ${teamNames.length} teams to src/lib/players.js`);
